### ISSUE TITLE
SampleSheet.csv file missing

### ISSUE THREAD

**Issue by hjames1** [lifei176/Single-cell-multi-omics#1]
Hi! Thank you for sharing. Could you kindly provide "SampleSheet.csv" file and the corresponding files needed to construct the "consensus_peakset" object in "2.ATAC_object_construction.R"?
or if the files needed are too large, could you just share the "consensus_peakset" object?

**Comment by lifei176** [comment]
[SampleSheet.csv](https://github.com/lifei176/Single-cell-multi-omics/files/10820788/SampleSheet.csv)
Sure, see attachment. Also, actually, you can construct this file directly. Please see the relative instruction at "https://bioconductor.org/packages/release/bioc/html/DiffBind.html".

**Comment by hjames1** [comment]
Thanks!
I notice the bed file in the Peaks column (e.g. atac_peaks_1M_1.bed), how should I get it?

**Comment by justin7777777** [comment]
Hi lifei176,

I have a question regarding code lines 334-338 in your repository. The code block is as follows:
```
#BiocManager::install("DiffBind")
#library(amap)
library(DiffBind)
data<-"SampleSheet.csv"
```
In order to obtain common peaks, the "SampleSheet.csv" file requires the following files:
```
atac_peaks_1M_1.bed
atac_peaks_1M_2.bed
atac_peaks_2_5M_1.bed
atac_peaks_2_5M_2.bed
atac_peaks_2_5M_3.bed
atac_peaks_2_5M_4.bed
atac_peaks_2W_1.bed
atac_peaks_2W_2.bed
atac_peaks_3_5M_1.bed
atac_peaks_3_5M_2.bed
atac_peaks_4_5M_1.bed
atac_peaks_4_5M_2.bed
atac_peaks_RC.bed
atac_peaks_WT1.bed
atac_peaks_WT2.bed
```
However, these files are not provided in https://ngdc.cncb.ac.cn/omix/release/OMIX001928. Could you please provide these files? Thank you very much.

**Comment by justin7777777** [comment]
> Thanks! I notice the bed file in the Peaks column (e.g. atac_peaks_1M_1.bed), how should I get it?

 It seems that they were not provided in the dataset we are using. Without these files, we won't be able to proceed with the next step.

**Comment by lifei176** [comment]
[peak_file.zip](https://github.com/lifei176/Single-cell-multi-omics/files/11658774/peak_file.zip)
Please see attached ZIP file (peak file).

**Comment by justin7777777** [comment]
> [peak_file.zip](https://github.com/lifei176/Single-cell-multi-omics/files/11658774/peak_file.zip) Please see attached ZIP file (peak file).
Thank you vey much!
